/*********************************************
 *           Code generated by the           *
 * Altibase Precompiler2(APRE) Ver.1(6.5.1.2.4_13)*
 *********************************************/

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ulpLibInterface.h>

/* The variable _esqlopts specifies command-line options
 * {-n, -unsafe_null, stmt caching, ...}
 */
static short _esqlopts[10] = {0,0,1,0,0,0,0,0,0,0};

#include <assert.h>
#include <limits.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>

#define ASSERT_SQL                                                      \
    if ( sqlca.sqlcode != SQL_SUCCESS ) {                               \
        printf( "Error : [%d] %s\n", SQLCODE, sqlca.sqlerrm.sqlerrmc ); \
        abort();                                                        \
    }

typedef struct threadContext {
    pthread_mutex_t connected;
    char            connection[1024];
    int             minimum;
    int             maximum;
    long long       sum;
    int             numberOfTransactions;
    int             numberOfLongTransactions;
} threadContext;

int numberOfThreads;
int startValue;
int numberOfTransactions;
int sizeOfUnit;
int threshold;
int cap;

struct timeval connectTime;
struct timeval startTime;
struct timeval endTime;

pthread_mutex_t* mutex;
int*             remain;
int*             cursor;
int*             allocated;


char user[1024];
char password[1024];
char option[1024];
char test_mode[1024];


int compareThreadContexts ( const void* element1, const void* element2 ) {
    
    const threadContext* context1;
    const threadContext* context2;
    
    context1 = (const threadContext*)element1;
    context2 = (const threadContext*)element2;
    
    if ( context1->numberOfTransactions < context2->numberOfTransactions ) return -1;
    if ( context1->numberOfTransactions > context2->numberOfTransactions ) return  1;
    
    return 0;
    
}

int allocateUnit ( int* start, int* end ) {
    
    int size;
    int elapsed;
    
    assert( pthread_mutex_lock( mutex ) == 0 );
    
    if ( cap > 0 ) {
        assert( gettimeofday( &endTime, NULL ) == 0 );
        if ( endTime.tv_usec > startTime.tv_usec ) {
            elapsed = ( endTime.tv_sec  - startTime.tv_sec ) * 1000000 + ( endTime.tv_usec - startTime.tv_usec );
        } else {
            elapsed = ( endTime.tv_sec  - 1 - startTime.tv_sec ) * 1000000 + ( endTime.tv_usec + 1000000 - startTime.tv_usec );
        }
        while ( (double)(*allocated) / ( (double)elapsed / 1000000. ) > (double)cap ) {
            sched_yield();
            assert( gettimeofday( &endTime, NULL ) == 0 );
            if ( endTime.tv_usec > startTime.tv_usec ) {
                elapsed = ( endTime.tv_sec  - startTime.tv_sec ) * 1000000 + ( endTime.tv_usec - startTime.tv_usec );
            } else {
                elapsed = ( endTime.tv_sec  - 1 - startTime.tv_sec ) * 1000000 + ( endTime.tv_usec + 1000000 - startTime.tv_usec );
            }
        }
    }
    
    if ( (*remain) > sizeOfUnit ) {
        size       = sizeOfUnit;
        (*remain) -= sizeOfUnit;
    } else {
        size       = (*remain);
        (*remain) -= (*remain);
    }
    *start        = (*cursor);
    *end          = (*cursor) + size;
    (*cursor)    += size;
    (*allocated) += size;
    
    assert( pthread_mutex_unlock( mutex ) == 0 );
    
    return size;
      
}

char* workingDirectory() {
    
    static char buffer[4096];
    
    char* directory;
    char* home;
    
    directory = getcwd( buffer, sizeof(buffer) - 1 );
    home      = getenv( "STANDARD_WORK" );
    
    assert( directory != NULL );
    if ( home != NULL ) {
        if ( strncmp( directory, home, strlen( home ) ) == 0 ) {
            directory += strlen( home );
        }
    }
    while( *directory == '/' || *directory == '\\' ) {
        directory++;
    }
    
    return directory;
        
}
void writeResult( char* mode, int dimension, int axis1, double axis2, double LongTransaction, int minimum, int maximum, int average ) {

    char* result;
    char* date;
    char* host;
    char* revision;
    char  filename[4096];
    FILE* file;
    char* interface;
    char* totalthread;
    char* product;
    char* unit;
    char* name;

    result = getenv( "STANDARD_RESULT" );

    if ( result != NULL ) {

        date = getenv( "STANDARD_DATE" );
        if ( date == NULL ) {
            date = "YYYYMMDD";
        }
        interface = getenv( "STANDARD_INTERFACE" );
        if ( interface == NULL ){
            interface = "unknown";
        }
        host = getenv( "STANDARD_HOST" );
        if ( host == NULL ) {
            host = "NOHOST";
        }
        totalthread = getenv( "STANDARD_ALLTHREAD" );
        if ( totalthread == NULL ) {
            totalthread = "0";
        }
        
        revision = getenv( "STANDARD_REVISION" );
        if ( revision == NULL ){
            revision = "unknown";
        }
        product = getenv( "STANDARD_PRODUCT" );
        if ( product == NULL ){
            product = "unknown";
        }
        unit = "TPS";
        name = "STANDARDBMT";

        sprintf( filename, "%s/%s_HDB-APRE_%s.sql", result, host, date );
        file = fopen( filename, "a" );
        assert( file != NULL );

        switch ( dimension ) {
         case 1:
            break;
         case 2:
            fprintf( file, "%s, %s, %s, %s, %s, %s, %s, %s, %d, %s, %.2f, %.2f, %d, %d, %d \n", date, host, product, revision, name, mode, interface, totalthread, axis1, unit, axis2, LongTransaction, minimum, maximum, average );
            break;
         default:
            assert( dimension == 1 || dimension == 2 ) ;
            break;
        }

        assert( fclose( file ) == 0 );

    }

}
void* worker ( void* argument ) {
    
    
    char   connection[1024];
    int    k01;
    char   k02[12];
    char   k03[12];
    char   k04[11];
    char   k05[11];
    char   k06[11];
    char   k07[21];
    char   k08[21];
    char   k09[21];
    char   k10[21];
    double k11;
    double k12;
    double k13;
    char   k14[11];
    char   k15[51];
    char   k16[51];
    char   k17[51];
    char   k18[51];
    int    k19;
    int    k20;
    char   k21[4];
    char   k22[4];
    char   k23[11];
    int    k24;
    int    k25;
    int    k26;
    int    k27;
    char   k28[31];  
    char   k29[31];  
    char   k30[31];  
    char   k31[12];
    double k32;
    double k33;
    int    k34;
    int    k35;
    char   k36[11];
    char   k37[11];
    char   k38[101];  
    char   k39[101];  
    char   k40[101];  
    int    k41;
    int    k42;
    int    k43;
    double k44;
    double k45;
    char   k46[11];
    char   k47[11];
    char   k48[12];
    char   k49[12];
    char   k50[21];
    char   k51[12];
    int    k52;
    int    k53;
    char   k54[12];
    char   k55[21];
    char   k56[21];
    char   k57[21];
    double k58;
    int    k59;
    char   k60[301];
    
    
    int            start;
    int            end;
    int            value;
    double	   dvalue;
    struct timeval startTime;
    struct timeval endTime;
    int            elapsed;

    dvalue = 12345.67809;
    
    k11 = dvalue;
    k12 = dvalue;
    k13 = dvalue;
    k32 = dvalue;
    k33 = dvalue;
    k44 = dvalue;
    k45 = dvalue;
    k58 = dvalue;

    memset( k02, 0, sizeof(k02) );
    memset( k03, 0, sizeof(k03) );
    memset( k04, 0, sizeof(k04) );
    memset( k05, 0, sizeof(k05) );
    memset( k06, 0, sizeof(k06) );
    memset( k07, 0, sizeof(k07) );
    memset( k08, 0, sizeof(k08) );
    memset( k09, 0, sizeof(k09) );
    memset( k10, 0, sizeof(k10) );
    memset( k14, 0, sizeof(k14) );
    memset( k15, 0, sizeof(k15) );
    memset( k16, 0, sizeof(k16) );
    memset( k17, 0, sizeof(k17) );
    memset( k18, 0, sizeof(k18) );
    memset( k21, 0, sizeof(k21) );
    memset( k22, 0, sizeof(k22) );
    memset( k23, 0, sizeof(k23) );
    memset( k28, 0, sizeof(k28) );
    memset( k29, 0, sizeof(k29) );
    memset( k30, 0, sizeof(k30) );
    memset( k31, 0, sizeof(k31) );
    memset( k36, 0, sizeof(k36) );
    memset( k37, 0, sizeof(k37) );
    memset( k38, 0, sizeof(k38) );
    memset( k39, 0, sizeof(k39) );
    memset( k40, 0, sizeof(k40) );
    memset( k46, 0, sizeof(k46) );
    memset( k47, 0, sizeof(k47) );
    memset( k48, 0, sizeof(k48) );
    memset( k49, 0, sizeof(k49) );
    memset( k50, 0, sizeof(k50) );
    memset( k51, 0, sizeof(k51) );
    memset( k54, 0, sizeof(k54) );
    memset( k55, 0, sizeof(k55) );
    memset( k56, 0, sizeof(k56) );
    memset( k57, 0, sizeof(k57) );
    memset( k60, 0, sizeof(k60) );
    strcpy( k02, "22-DEC-2014" );
    strcpy( k03, "22-DEC-2014" );
    strcpy( k04, "abcdefghij" );
    strcpy( k05, "abcdefghij" );
    strcpy( k06, "abcdefghij" );
    strcpy( k07, "abcdefghijklmnopq" );
    strcpy( k08, "abcdefghijklmnopqr" );
    strcpy( k09, "abcdefghijklmnopqrs" );
    strcpy( k10, "abcdefghijklmnopqrst" );
    strcpy( k14, "abcdefghij" );
    strcpy( k15, "abcdefghijklmnopqrst          abcdefghijklmnopqrst" );
    strcpy( k16, "abcdefghijklmnopqrst     abcdefghijklmnopqrst" );
    strcpy( k17, "     abcdefghijklmnopqrst     abcdefghijklmnopqrst" );
    strcpy( k18, " abcdefghijklmnopqrst        abcdefghijklmnopqrst " );
    strcpy( k21, "abs" );
    strcpy( k22, "xyz" );
    strcpy( k23, "abcdefghij" );
    strcpy( k28, "abcdefghijklmnopqrstuvwxyz0123" );
    strcpy( k29, "abcdefghijklmnopqrstuvwxyz0123" );
    strcpy( k30, "abcdefghijklmnopqrstuvwxyz0123" );
    strcpy( k31, "22-DEC-2014" );
    strcpy( k36, "abcdefghij" );
    strcpy( k37, "abcdefghij" );
    strcpy( k38, "abcdefghijklmnopqrstuvwxyz0123abcdefghijklmnopqrstuvwxyz0123abcdefghijklmnopqrstuvwxyz01230123456789" );
    strcpy( k39, "abcdefghijklmnopqrstuvwxyz0123abcdefghijklmnopqrstuvwxyz0123abcdefghijklmnopqrstuvwxyz01230123456789" );
    strcpy( k40, "abcdefghijklmnopqrstuvwxyz0123abcdefghijklmnopqrstuvwxyz0123abcdefghijklmnopqrstuvwxyz01230123456789" );
    strcpy( k46, "abcdefghij" );
    strcpy( k47, "abcdefghij" );
    strcpy( k48, "22-DEC-2014" );
    strcpy( k49, "22-DEC-2014" );
    strcpy( k50, "abcdefghijklmnopqrst" );
    strcpy( k51, "22-DEC-2014" );
    strcpy( k54, "22-DEC-2014" );
    strcpy( k55, "abcdefghijklmnopqrst" );
    strcpy( k56, "abcdefghijklmnopqrst" );
    strcpy( k57, "abcdefghijklmnopqrst" );
    strcpy( k60, "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz1234567890okOK" );
    
    threadContext* context = (threadContext*)argument;
    
    strcpy( connection, context->connection );
    
    /*                 CONNECT :user IDENTIFIED BY :password USING :option; */
{
    struct ulpSqlstmt ulpSqlstmt;
    memset(&ulpSqlstmt, 0, sizeof(ulpSqlstmt));
    ulpHostVar ulpHostVar[3];
    ulpSqlstmt.hostvalue = ulpHostVar;
    ulpSqlstmt.stmttype = 1;
    ulpSqlstmt.stmtname = NULL;
    ulpSqlstmt.ismt = 1;
    ulpSqlstmt.sqlinfo = 0;
    ulpSqlstmt.numofhostvar = 3;
    ulpSqlstmt.esqlopts    = _esqlopts;
    ulpSqlstmt.sqlcaerr    = &sqlca;
    ulpSqlstmt.sqlcodeerr  = &SQLCODE;
    ulpSqlstmt.sqlstateerr = ulpGetSqlstate();
    ulpSqlstmt.hostvalue[0].mHostVar = (void*)user;
    ulpSqlstmt.hostvalue[1].mHostVar = (void*)password;
    ulpSqlstmt.hostvalue[2].mHostVar = (void*)option;
    ulpDoEmsql( (char*) connection, &ulpSqlstmt, NULL );
}

    ASSERT_SQL;
    
    assert( pthread_mutex_unlock( &(context->connected) ) == 0 );
    
    while ( allocateUnit( &start, &end ) > 0 ) {
        
        for ( value = start; value < end; value++ ) {
            
            assert( gettimeofday( &startTime, NULL ) == 0 );

            k01 = value;
            k19 = value;
            k20 = value;
            k24 = value;
            k25 = value;
            k26 = value;
            k27 = value;
            k34 = value;
            k35 = value;
            k41 = value;
            k42 = value;
            k43 = value;
            k52 = value;
            k53 = value;
            k59 = value;
            
            /*                 INSERT INTO TEST 
                                       VALUES ( :k01, :k02, :k03, :k04, :k05, :k06, :k07, :k08, :k09, :k10,  
                                                :k11, :k12, :k13, :k14, :k15, :k16, :k17, :k18, :k19, :k20, 
                                                :k21, :k22, :k23, :k24, :k25, :k26, :k27, :k28, :k29, :k30,  
                                                :k31, :k32, :k33, :k34, :k35, :k36, :k37, :k38, :k39, :k40,  
                                                :k41, :k42, :k43, :k44, :k45, :k46, :k47, :k48, :k49, :k50, 
                                                :k51, :k52, :k53, :k54, :k55, :k56, :k57, :k58, :k59, :k60 ); */
{
    struct ulpSqlstmt ulpSqlstmt;
    memset(&ulpSqlstmt, 0, sizeof(ulpSqlstmt));
    ulpHostVar ulpHostVar[60];
    ulpSqlstmt.hostvalue = ulpHostVar;
    ulpSqlstmt.stmttype = 3;
    ulpSqlstmt.stmtname = NULL;
    ulpSqlstmt.ismt = 1;
    ulpSqlstmt.numofhostvar = 60;
    ulpSqlstmt.statusptr = NULL;
    ulpSqlstmt.errcodeptr = NULL;
    ulpSqlstmt.isatomic = 0;
    ulpSqlstmt.stmt = (char *)"INSERT INTO TEST "
"                                       VALUES ( ? , ? , ? , ? , ? , ? , ? , ? , ? , ? ,  "
"                                                ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , "
"                                                ? , ? , ? , ? , ? , ? , ? , ? , ? , ? ,  "
"                                                ? , ? , ? , ? , ? , ? , ? , ? , ? , ? ,  "
"                                                ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , "
"                                                ? , ? , ? , ? , ? , ? , ? , ? , ? , ?  )";
    ulpSqlstmt.iters = 0;
    ulpSqlstmt.sqlinfo = 0;
    ulpSqlstmt.scrollcur = 0;
    ulpSqlstmt.cursorscrollable = 0;
    ulpSqlstmt.cursorsensitivity = 1;
    ulpSqlstmt.cursorwithhold = 0;
    ulpSqlstmt.esqlopts    = _esqlopts;
    ulpSqlstmt.sqlcaerr    = &sqlca;
    ulpSqlstmt.sqlcodeerr  = &SQLCODE;
    ulpSqlstmt.sqlstateerr = ulpGetSqlstate();
    ulpSqlstmt.hostvalue[0].mHostVar = (void*)&(k01);
    ulpSqlstmt.hostvalue[0].mHostInd = NULL;
    ulpSqlstmt.hostvalue[0].isarr = 0;
    ulpSqlstmt.hostvalue[0].mType = 2;
    ulpSqlstmt.hostvalue[0].isstruct = 0;
    ulpSqlstmt.hostvalue[0].mSizeof = sizeof(int);
    ulpSqlstmt.hostvalue[0].mLen = 0;
    ulpSqlstmt.hostvalue[0].mMaxlen = 0;
    ulpSqlstmt.hostvalue[0].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[0].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[0].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[1].mHostVar = (void*)(k02);
    ulpSqlstmt.hostvalue[1].mHostInd = NULL;
    ulpSqlstmt.hostvalue[1].isarr = 0;
    ulpSqlstmt.hostvalue[1].mType = 6;
    ulpSqlstmt.hostvalue[1].isstruct = 0;
    ulpSqlstmt.hostvalue[1].mSizeof = 0;
    ulpSqlstmt.hostvalue[1].mLen = 12;
    ulpSqlstmt.hostvalue[1].mMaxlen = sizeof(k02);
    ulpSqlstmt.hostvalue[1].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[1].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[1].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[2].mHostVar = (void*)(k03);
    ulpSqlstmt.hostvalue[2].mHostInd = NULL;
    ulpSqlstmt.hostvalue[2].isarr = 0;
    ulpSqlstmt.hostvalue[2].mType = 6;
    ulpSqlstmt.hostvalue[2].isstruct = 0;
    ulpSqlstmt.hostvalue[2].mSizeof = 0;
    ulpSqlstmt.hostvalue[2].mLen = 12;
    ulpSqlstmt.hostvalue[2].mMaxlen = sizeof(k03);
    ulpSqlstmt.hostvalue[2].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[2].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[2].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[3].mHostVar = (void*)(k04);
    ulpSqlstmt.hostvalue[3].mHostInd = NULL;
    ulpSqlstmt.hostvalue[3].isarr = 0;
    ulpSqlstmt.hostvalue[3].mType = 6;
    ulpSqlstmt.hostvalue[3].isstruct = 0;
    ulpSqlstmt.hostvalue[3].mSizeof = 0;
    ulpSqlstmt.hostvalue[3].mLen = 11;
    ulpSqlstmt.hostvalue[3].mMaxlen = sizeof(k04);
    ulpSqlstmt.hostvalue[3].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[3].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[3].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[4].mHostVar = (void*)(k05);
    ulpSqlstmt.hostvalue[4].mHostInd = NULL;
    ulpSqlstmt.hostvalue[4].isarr = 0;
    ulpSqlstmt.hostvalue[4].mType = 6;
    ulpSqlstmt.hostvalue[4].isstruct = 0;
    ulpSqlstmt.hostvalue[4].mSizeof = 0;
    ulpSqlstmt.hostvalue[4].mLen = 11;
    ulpSqlstmt.hostvalue[4].mMaxlen = sizeof(k05);
    ulpSqlstmt.hostvalue[4].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[4].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[4].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[5].mHostVar = (void*)(k06);
    ulpSqlstmt.hostvalue[5].mHostInd = NULL;
    ulpSqlstmt.hostvalue[5].isarr = 0;
    ulpSqlstmt.hostvalue[5].mType = 6;
    ulpSqlstmt.hostvalue[5].isstruct = 0;
    ulpSqlstmt.hostvalue[5].mSizeof = 0;
    ulpSqlstmt.hostvalue[5].mLen = 11;
    ulpSqlstmt.hostvalue[5].mMaxlen = sizeof(k06);
    ulpSqlstmt.hostvalue[5].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[5].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[5].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[6].mHostVar = (void*)(k07);
    ulpSqlstmt.hostvalue[6].mHostInd = NULL;
    ulpSqlstmt.hostvalue[6].isarr = 0;
    ulpSqlstmt.hostvalue[6].mType = 6;
    ulpSqlstmt.hostvalue[6].isstruct = 0;
    ulpSqlstmt.hostvalue[6].mSizeof = 0;
    ulpSqlstmt.hostvalue[6].mLen = 21;
    ulpSqlstmt.hostvalue[6].mMaxlen = sizeof(k07);
    ulpSqlstmt.hostvalue[6].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[6].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[6].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[7].mHostVar = (void*)(k08);
    ulpSqlstmt.hostvalue[7].mHostInd = NULL;
    ulpSqlstmt.hostvalue[7].isarr = 0;
    ulpSqlstmt.hostvalue[7].mType = 6;
    ulpSqlstmt.hostvalue[7].isstruct = 0;
    ulpSqlstmt.hostvalue[7].mSizeof = 0;
    ulpSqlstmt.hostvalue[7].mLen = 21;
    ulpSqlstmt.hostvalue[7].mMaxlen = sizeof(k08);
    ulpSqlstmt.hostvalue[7].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[7].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[7].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[8].mHostVar = (void*)(k09);
    ulpSqlstmt.hostvalue[8].mHostInd = NULL;
    ulpSqlstmt.hostvalue[8].isarr = 0;
    ulpSqlstmt.hostvalue[8].mType = 6;
    ulpSqlstmt.hostvalue[8].isstruct = 0;
    ulpSqlstmt.hostvalue[8].mSizeof = 0;
    ulpSqlstmt.hostvalue[8].mLen = 21;
    ulpSqlstmt.hostvalue[8].mMaxlen = sizeof(k09);
    ulpSqlstmt.hostvalue[8].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[8].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[8].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[9].mHostVar = (void*)(k10);
    ulpSqlstmt.hostvalue[9].mHostInd = NULL;
    ulpSqlstmt.hostvalue[9].isarr = 0;
    ulpSqlstmt.hostvalue[9].mType = 6;
    ulpSqlstmt.hostvalue[9].isstruct = 0;
    ulpSqlstmt.hostvalue[9].mSizeof = 0;
    ulpSqlstmt.hostvalue[9].mLen = 21;
    ulpSqlstmt.hostvalue[9].mMaxlen = sizeof(k10);
    ulpSqlstmt.hostvalue[9].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[9].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[9].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[10].mHostVar = (void*)&(k11);
    ulpSqlstmt.hostvalue[10].mHostInd = NULL;
    ulpSqlstmt.hostvalue[10].isarr = 0;
    ulpSqlstmt.hostvalue[10].mType = 14;
    ulpSqlstmt.hostvalue[10].isstruct = 0;
    ulpSqlstmt.hostvalue[10].mSizeof = sizeof(double);
    ulpSqlstmt.hostvalue[10].mLen = 0;
    ulpSqlstmt.hostvalue[10].mMaxlen = 0;
    ulpSqlstmt.hostvalue[10].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[10].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[10].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[11].mHostVar = (void*)&(k12);
    ulpSqlstmt.hostvalue[11].mHostInd = NULL;
    ulpSqlstmt.hostvalue[11].isarr = 0;
    ulpSqlstmt.hostvalue[11].mType = 14;
    ulpSqlstmt.hostvalue[11].isstruct = 0;
    ulpSqlstmt.hostvalue[11].mSizeof = sizeof(double);
    ulpSqlstmt.hostvalue[11].mLen = 0;
    ulpSqlstmt.hostvalue[11].mMaxlen = 0;
    ulpSqlstmt.hostvalue[11].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[11].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[11].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[12].mHostVar = (void*)&(k13);
    ulpSqlstmt.hostvalue[12].mHostInd = NULL;
    ulpSqlstmt.hostvalue[12].isarr = 0;
    ulpSqlstmt.hostvalue[12].mType = 14;
    ulpSqlstmt.hostvalue[12].isstruct = 0;
    ulpSqlstmt.hostvalue[12].mSizeof = sizeof(double);
    ulpSqlstmt.hostvalue[12].mLen = 0;
    ulpSqlstmt.hostvalue[12].mMaxlen = 0;
    ulpSqlstmt.hostvalue[12].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[12].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[12].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[13].mHostVar = (void*)(k14);
    ulpSqlstmt.hostvalue[13].mHostInd = NULL;
    ulpSqlstmt.hostvalue[13].isarr = 0;
    ulpSqlstmt.hostvalue[13].mType = 6;
    ulpSqlstmt.hostvalue[13].isstruct = 0;
    ulpSqlstmt.hostvalue[13].mSizeof = 0;
    ulpSqlstmt.hostvalue[13].mLen = 11;
    ulpSqlstmt.hostvalue[13].mMaxlen = sizeof(k14);
    ulpSqlstmt.hostvalue[13].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[13].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[13].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[14].mHostVar = (void*)(k15);
    ulpSqlstmt.hostvalue[14].mHostInd = NULL;
    ulpSqlstmt.hostvalue[14].isarr = 0;
    ulpSqlstmt.hostvalue[14].mType = 6;
    ulpSqlstmt.hostvalue[14].isstruct = 0;
    ulpSqlstmt.hostvalue[14].mSizeof = 0;
    ulpSqlstmt.hostvalue[14].mLen = 51;
    ulpSqlstmt.hostvalue[14].mMaxlen = sizeof(k15);
    ulpSqlstmt.hostvalue[14].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[14].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[14].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[15].mHostVar = (void*)(k16);
    ulpSqlstmt.hostvalue[15].mHostInd = NULL;
    ulpSqlstmt.hostvalue[15].isarr = 0;
    ulpSqlstmt.hostvalue[15].mType = 6;
    ulpSqlstmt.hostvalue[15].isstruct = 0;
    ulpSqlstmt.hostvalue[15].mSizeof = 0;
    ulpSqlstmt.hostvalue[15].mLen = 51;
    ulpSqlstmt.hostvalue[15].mMaxlen = sizeof(k16);
    ulpSqlstmt.hostvalue[15].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[15].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[15].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[16].mHostVar = (void*)(k17);
    ulpSqlstmt.hostvalue[16].mHostInd = NULL;
    ulpSqlstmt.hostvalue[16].isarr = 0;
    ulpSqlstmt.hostvalue[16].mType = 6;
    ulpSqlstmt.hostvalue[16].isstruct = 0;
    ulpSqlstmt.hostvalue[16].mSizeof = 0;
    ulpSqlstmt.hostvalue[16].mLen = 51;
    ulpSqlstmt.hostvalue[16].mMaxlen = sizeof(k17);
    ulpSqlstmt.hostvalue[16].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[16].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[16].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[17].mHostVar = (void*)(k18);
    ulpSqlstmt.hostvalue[17].mHostInd = NULL;
    ulpSqlstmt.hostvalue[17].isarr = 0;
    ulpSqlstmt.hostvalue[17].mType = 6;
    ulpSqlstmt.hostvalue[17].isstruct = 0;
    ulpSqlstmt.hostvalue[17].mSizeof = 0;
    ulpSqlstmt.hostvalue[17].mLen = 51;
    ulpSqlstmt.hostvalue[17].mMaxlen = sizeof(k18);
    ulpSqlstmt.hostvalue[17].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[17].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[17].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[18].mHostVar = (void*)&(k19);
    ulpSqlstmt.hostvalue[18].mHostInd = NULL;
    ulpSqlstmt.hostvalue[18].isarr = 0;
    ulpSqlstmt.hostvalue[18].mType = 2;
    ulpSqlstmt.hostvalue[18].isstruct = 0;
    ulpSqlstmt.hostvalue[18].mSizeof = sizeof(int);
    ulpSqlstmt.hostvalue[18].mLen = 0;
    ulpSqlstmt.hostvalue[18].mMaxlen = 0;
    ulpSqlstmt.hostvalue[18].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[18].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[18].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[19].mHostVar = (void*)&(k20);
    ulpSqlstmt.hostvalue[19].mHostInd = NULL;
    ulpSqlstmt.hostvalue[19].isarr = 0;
    ulpSqlstmt.hostvalue[19].mType = 2;
    ulpSqlstmt.hostvalue[19].isstruct = 0;
    ulpSqlstmt.hostvalue[19].mSizeof = sizeof(int);
    ulpSqlstmt.hostvalue[19].mLen = 0;
    ulpSqlstmt.hostvalue[19].mMaxlen = 0;
    ulpSqlstmt.hostvalue[19].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[19].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[19].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[20].mHostVar = (void*)(k21);
    ulpSqlstmt.hostvalue[20].mHostInd = NULL;
    ulpSqlstmt.hostvalue[20].isarr = 0;
    ulpSqlstmt.hostvalue[20].mType = 6;
    ulpSqlstmt.hostvalue[20].isstruct = 0;
    ulpSqlstmt.hostvalue[20].mSizeof = 0;
    ulpSqlstmt.hostvalue[20].mLen = 4;
    ulpSqlstmt.hostvalue[20].mMaxlen = sizeof(k21);
    ulpSqlstmt.hostvalue[20].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[20].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[20].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[21].mHostVar = (void*)(k22);
    ulpSqlstmt.hostvalue[21].mHostInd = NULL;
    ulpSqlstmt.hostvalue[21].isarr = 0;
    ulpSqlstmt.hostvalue[21].mType = 6;
    ulpSqlstmt.hostvalue[21].isstruct = 0;
    ulpSqlstmt.hostvalue[21].mSizeof = 0;
    ulpSqlstmt.hostvalue[21].mLen = 4;
    ulpSqlstmt.hostvalue[21].mMaxlen = sizeof(k22);
    ulpSqlstmt.hostvalue[21].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[21].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[21].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[22].mHostVar = (void*)(k23);
    ulpSqlstmt.hostvalue[22].mHostInd = NULL;
    ulpSqlstmt.hostvalue[22].isarr = 0;
    ulpSqlstmt.hostvalue[22].mType = 6;
    ulpSqlstmt.hostvalue[22].isstruct = 0;
    ulpSqlstmt.hostvalue[22].mSizeof = 0;
    ulpSqlstmt.hostvalue[22].mLen = 11;
    ulpSqlstmt.hostvalue[22].mMaxlen = sizeof(k23);
    ulpSqlstmt.hostvalue[22].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[22].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[22].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[23].mHostVar = (void*)&(k24);
    ulpSqlstmt.hostvalue[23].mHostInd = NULL;
    ulpSqlstmt.hostvalue[23].isarr = 0;
    ulpSqlstmt.hostvalue[23].mType = 2;
    ulpSqlstmt.hostvalue[23].isstruct = 0;
    ulpSqlstmt.hostvalue[23].mSizeof = sizeof(int);
    ulpSqlstmt.hostvalue[23].mLen = 0;
    ulpSqlstmt.hostvalue[23].mMaxlen = 0;
    ulpSqlstmt.hostvalue[23].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[23].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[23].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[24].mHostVar = (void*)&(k25);
    ulpSqlstmt.hostvalue[24].mHostInd = NULL;
    ulpSqlstmt.hostvalue[24].isarr = 0;
    ulpSqlstmt.hostvalue[24].mType = 2;
    ulpSqlstmt.hostvalue[24].isstruct = 0;
    ulpSqlstmt.hostvalue[24].mSizeof = sizeof(int);
    ulpSqlstmt.hostvalue[24].mLen = 0;
    ulpSqlstmt.hostvalue[24].mMaxlen = 0;
    ulpSqlstmt.hostvalue[24].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[24].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[24].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[25].mHostVar = (void*)&(k26);
    ulpSqlstmt.hostvalue[25].mHostInd = NULL;
    ulpSqlstmt.hostvalue[25].isarr = 0;
    ulpSqlstmt.hostvalue[25].mType = 2;
    ulpSqlstmt.hostvalue[25].isstruct = 0;
    ulpSqlstmt.hostvalue[25].mSizeof = sizeof(int);
    ulpSqlstmt.hostvalue[25].mLen = 0;
    ulpSqlstmt.hostvalue[25].mMaxlen = 0;
    ulpSqlstmt.hostvalue[25].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[25].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[25].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[26].mHostVar = (void*)&(k27);
    ulpSqlstmt.hostvalue[26].mHostInd = NULL;
    ulpSqlstmt.hostvalue[26].isarr = 0;
    ulpSqlstmt.hostvalue[26].mType = 2;
    ulpSqlstmt.hostvalue[26].isstruct = 0;
    ulpSqlstmt.hostvalue[26].mSizeof = sizeof(int);
    ulpSqlstmt.hostvalue[26].mLen = 0;
    ulpSqlstmt.hostvalue[26].mMaxlen = 0;
    ulpSqlstmt.hostvalue[26].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[26].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[26].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[27].mHostVar = (void*)(k28);
    ulpSqlstmt.hostvalue[27].mHostInd = NULL;
    ulpSqlstmt.hostvalue[27].isarr = 0;
    ulpSqlstmt.hostvalue[27].mType = 6;
    ulpSqlstmt.hostvalue[27].isstruct = 0;
    ulpSqlstmt.hostvalue[27].mSizeof = 0;
    ulpSqlstmt.hostvalue[27].mLen = 31;
    ulpSqlstmt.hostvalue[27].mMaxlen = sizeof(k28);
    ulpSqlstmt.hostvalue[27].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[27].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[27].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[28].mHostVar = (void*)(k29);
    ulpSqlstmt.hostvalue[28].mHostInd = NULL;
    ulpSqlstmt.hostvalue[28].isarr = 0;
    ulpSqlstmt.hostvalue[28].mType = 6;
    ulpSqlstmt.hostvalue[28].isstruct = 0;
    ulpSqlstmt.hostvalue[28].mSizeof = 0;
    ulpSqlstmt.hostvalue[28].mLen = 31;
    ulpSqlstmt.hostvalue[28].mMaxlen = sizeof(k29);
    ulpSqlstmt.hostvalue[28].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[28].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[28].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[29].mHostVar = (void*)(k30);
    ulpSqlstmt.hostvalue[29].mHostInd = NULL;
    ulpSqlstmt.hostvalue[29].isarr = 0;
    ulpSqlstmt.hostvalue[29].mType = 6;
    ulpSqlstmt.hostvalue[29].isstruct = 0;
    ulpSqlstmt.hostvalue[29].mSizeof = 0;
    ulpSqlstmt.hostvalue[29].mLen = 31;
    ulpSqlstmt.hostvalue[29].mMaxlen = sizeof(k30);
    ulpSqlstmt.hostvalue[29].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[29].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[29].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[30].mHostVar = (void*)(k31);
    ulpSqlstmt.hostvalue[30].mHostInd = NULL;
    ulpSqlstmt.hostvalue[30].isarr = 0;
    ulpSqlstmt.hostvalue[30].mType = 6;
    ulpSqlstmt.hostvalue[30].isstruct = 0;
    ulpSqlstmt.hostvalue[30].mSizeof = 0;
    ulpSqlstmt.hostvalue[30].mLen = 12;
    ulpSqlstmt.hostvalue[30].mMaxlen = sizeof(k31);
    ulpSqlstmt.hostvalue[30].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[30].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[30].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[31].mHostVar = (void*)&(k32);
    ulpSqlstmt.hostvalue[31].mHostInd = NULL;
    ulpSqlstmt.hostvalue[31].isarr = 0;
    ulpSqlstmt.hostvalue[31].mType = 14;
    ulpSqlstmt.hostvalue[31].isstruct = 0;
    ulpSqlstmt.hostvalue[31].mSizeof = sizeof(double);
    ulpSqlstmt.hostvalue[31].mLen = 0;
    ulpSqlstmt.hostvalue[31].mMaxlen = 0;
    ulpSqlstmt.hostvalue[31].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[31].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[31].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[32].mHostVar = (void*)&(k33);
    ulpSqlstmt.hostvalue[32].mHostInd = NULL;
    ulpSqlstmt.hostvalue[32].isarr = 0;
    ulpSqlstmt.hostvalue[32].mType = 14;
    ulpSqlstmt.hostvalue[32].isstruct = 0;
    ulpSqlstmt.hostvalue[32].mSizeof = sizeof(double);
    ulpSqlstmt.hostvalue[32].mLen = 0;
    ulpSqlstmt.hostvalue[32].mMaxlen = 0;
    ulpSqlstmt.hostvalue[32].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[32].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[32].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[33].mHostVar = (void*)&(k34);
    ulpSqlstmt.hostvalue[33].mHostInd = NULL;
    ulpSqlstmt.hostvalue[33].isarr = 0;
    ulpSqlstmt.hostvalue[33].mType = 2;
    ulpSqlstmt.hostvalue[33].isstruct = 0;
    ulpSqlstmt.hostvalue[33].mSizeof = sizeof(int);
    ulpSqlstmt.hostvalue[33].mLen = 0;
    ulpSqlstmt.hostvalue[33].mMaxlen = 0;
    ulpSqlstmt.hostvalue[33].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[33].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[33].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[34].mHostVar = (void*)&(k35);
    ulpSqlstmt.hostvalue[34].mHostInd = NULL;
    ulpSqlstmt.hostvalue[34].isarr = 0;
    ulpSqlstmt.hostvalue[34].mType = 2;
    ulpSqlstmt.hostvalue[34].isstruct = 0;
    ulpSqlstmt.hostvalue[34].mSizeof = sizeof(int);
    ulpSqlstmt.hostvalue[34].mLen = 0;
    ulpSqlstmt.hostvalue[34].mMaxlen = 0;
    ulpSqlstmt.hostvalue[34].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[34].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[34].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[35].mHostVar = (void*)(k36);
    ulpSqlstmt.hostvalue[35].mHostInd = NULL;
    ulpSqlstmt.hostvalue[35].isarr = 0;
    ulpSqlstmt.hostvalue[35].mType = 6;
    ulpSqlstmt.hostvalue[35].isstruct = 0;
    ulpSqlstmt.hostvalue[35].mSizeof = 0;
    ulpSqlstmt.hostvalue[35].mLen = 11;
    ulpSqlstmt.hostvalue[35].mMaxlen = sizeof(k36);
    ulpSqlstmt.hostvalue[35].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[35].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[35].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[36].mHostVar = (void*)(k37);
    ulpSqlstmt.hostvalue[36].mHostInd = NULL;
    ulpSqlstmt.hostvalue[36].isarr = 0;
    ulpSqlstmt.hostvalue[36].mType = 6;
    ulpSqlstmt.hostvalue[36].isstruct = 0;
    ulpSqlstmt.hostvalue[36].mSizeof = 0;
    ulpSqlstmt.hostvalue[36].mLen = 11;
    ulpSqlstmt.hostvalue[36].mMaxlen = sizeof(k37);
    ulpSqlstmt.hostvalue[36].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[36].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[36].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[37].mHostVar = (void*)(k38);
    ulpSqlstmt.hostvalue[37].mHostInd = NULL;
    ulpSqlstmt.hostvalue[37].isarr = 0;
    ulpSqlstmt.hostvalue[37].mType = 6;
    ulpSqlstmt.hostvalue[37].isstruct = 0;
    ulpSqlstmt.hostvalue[37].mSizeof = 0;
    ulpSqlstmt.hostvalue[37].mLen = 101;
    ulpSqlstmt.hostvalue[37].mMaxlen = sizeof(k38);
    ulpSqlstmt.hostvalue[37].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[37].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[37].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[38].mHostVar = (void*)(k39);
    ulpSqlstmt.hostvalue[38].mHostInd = NULL;
    ulpSqlstmt.hostvalue[38].isarr = 0;
    ulpSqlstmt.hostvalue[38].mType = 6;
    ulpSqlstmt.hostvalue[38].isstruct = 0;
    ulpSqlstmt.hostvalue[38].mSizeof = 0;
    ulpSqlstmt.hostvalue[38].mLen = 101;
    ulpSqlstmt.hostvalue[38].mMaxlen = sizeof(k39);
    ulpSqlstmt.hostvalue[38].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[38].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[38].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[39].mHostVar = (void*)(k40);
    ulpSqlstmt.hostvalue[39].mHostInd = NULL;
    ulpSqlstmt.hostvalue[39].isarr = 0;
    ulpSqlstmt.hostvalue[39].mType = 6;
    ulpSqlstmt.hostvalue[39].isstruct = 0;
    ulpSqlstmt.hostvalue[39].mSizeof = 0;
    ulpSqlstmt.hostvalue[39].mLen = 101;
    ulpSqlstmt.hostvalue[39].mMaxlen = sizeof(k40);
    ulpSqlstmt.hostvalue[39].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[39].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[39].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[40].mHostVar = (void*)&(k41);
    ulpSqlstmt.hostvalue[40].mHostInd = NULL;
    ulpSqlstmt.hostvalue[40].isarr = 0;
    ulpSqlstmt.hostvalue[40].mType = 2;
    ulpSqlstmt.hostvalue[40].isstruct = 0;
    ulpSqlstmt.hostvalue[40].mSizeof = sizeof(int);
    ulpSqlstmt.hostvalue[40].mLen = 0;
    ulpSqlstmt.hostvalue[40].mMaxlen = 0;
    ulpSqlstmt.hostvalue[40].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[40].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[40].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[41].mHostVar = (void*)&(k42);
    ulpSqlstmt.hostvalue[41].mHostInd = NULL;
    ulpSqlstmt.hostvalue[41].isarr = 0;
    ulpSqlstmt.hostvalue[41].mType = 2;
    ulpSqlstmt.hostvalue[41].isstruct = 0;
    ulpSqlstmt.hostvalue[41].mSizeof = sizeof(int);
    ulpSqlstmt.hostvalue[41].mLen = 0;
    ulpSqlstmt.hostvalue[41].mMaxlen = 0;
    ulpSqlstmt.hostvalue[41].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[41].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[41].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[42].mHostVar = (void*)&(k43);
    ulpSqlstmt.hostvalue[42].mHostInd = NULL;
    ulpSqlstmt.hostvalue[42].isarr = 0;
    ulpSqlstmt.hostvalue[42].mType = 2;
    ulpSqlstmt.hostvalue[42].isstruct = 0;
    ulpSqlstmt.hostvalue[42].mSizeof = sizeof(int);
    ulpSqlstmt.hostvalue[42].mLen = 0;
    ulpSqlstmt.hostvalue[42].mMaxlen = 0;
    ulpSqlstmt.hostvalue[42].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[42].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[42].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[43].mHostVar = (void*)&(k44);
    ulpSqlstmt.hostvalue[43].mHostInd = NULL;
    ulpSqlstmt.hostvalue[43].isarr = 0;
    ulpSqlstmt.hostvalue[43].mType = 14;
    ulpSqlstmt.hostvalue[43].isstruct = 0;
    ulpSqlstmt.hostvalue[43].mSizeof = sizeof(double);
    ulpSqlstmt.hostvalue[43].mLen = 0;
    ulpSqlstmt.hostvalue[43].mMaxlen = 0;
    ulpSqlstmt.hostvalue[43].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[43].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[43].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[44].mHostVar = (void*)&(k45);
    ulpSqlstmt.hostvalue[44].mHostInd = NULL;
    ulpSqlstmt.hostvalue[44].isarr = 0;
    ulpSqlstmt.hostvalue[44].mType = 14;
    ulpSqlstmt.hostvalue[44].isstruct = 0;
    ulpSqlstmt.hostvalue[44].mSizeof = sizeof(double);
    ulpSqlstmt.hostvalue[44].mLen = 0;
    ulpSqlstmt.hostvalue[44].mMaxlen = 0;
    ulpSqlstmt.hostvalue[44].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[44].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[44].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[45].mHostVar = (void*)(k46);
    ulpSqlstmt.hostvalue[45].mHostInd = NULL;
    ulpSqlstmt.hostvalue[45].isarr = 0;
    ulpSqlstmt.hostvalue[45].mType = 6;
    ulpSqlstmt.hostvalue[45].isstruct = 0;
    ulpSqlstmt.hostvalue[45].mSizeof = 0;
    ulpSqlstmt.hostvalue[45].mLen = 11;
    ulpSqlstmt.hostvalue[45].mMaxlen = sizeof(k46);
    ulpSqlstmt.hostvalue[45].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[45].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[45].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[46].mHostVar = (void*)(k47);
    ulpSqlstmt.hostvalue[46].mHostInd = NULL;
    ulpSqlstmt.hostvalue[46].isarr = 0;
    ulpSqlstmt.hostvalue[46].mType = 6;
    ulpSqlstmt.hostvalue[46].isstruct = 0;
    ulpSqlstmt.hostvalue[46].mSizeof = 0;
    ulpSqlstmt.hostvalue[46].mLen = 11;
    ulpSqlstmt.hostvalue[46].mMaxlen = sizeof(k47);
    ulpSqlstmt.hostvalue[46].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[46].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[46].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[47].mHostVar = (void*)(k48);
    ulpSqlstmt.hostvalue[47].mHostInd = NULL;
    ulpSqlstmt.hostvalue[47].isarr = 0;
    ulpSqlstmt.hostvalue[47].mType = 6;
    ulpSqlstmt.hostvalue[47].isstruct = 0;
    ulpSqlstmt.hostvalue[47].mSizeof = 0;
    ulpSqlstmt.hostvalue[47].mLen = 12;
    ulpSqlstmt.hostvalue[47].mMaxlen = sizeof(k48);
    ulpSqlstmt.hostvalue[47].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[47].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[47].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[48].mHostVar = (void*)(k49);
    ulpSqlstmt.hostvalue[48].mHostInd = NULL;
    ulpSqlstmt.hostvalue[48].isarr = 0;
    ulpSqlstmt.hostvalue[48].mType = 6;
    ulpSqlstmt.hostvalue[48].isstruct = 0;
    ulpSqlstmt.hostvalue[48].mSizeof = 0;
    ulpSqlstmt.hostvalue[48].mLen = 12;
    ulpSqlstmt.hostvalue[48].mMaxlen = sizeof(k49);
    ulpSqlstmt.hostvalue[48].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[48].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[48].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[49].mHostVar = (void*)(k50);
    ulpSqlstmt.hostvalue[49].mHostInd = NULL;
    ulpSqlstmt.hostvalue[49].isarr = 0;
    ulpSqlstmt.hostvalue[49].mType = 6;
    ulpSqlstmt.hostvalue[49].isstruct = 0;
    ulpSqlstmt.hostvalue[49].mSizeof = 0;
    ulpSqlstmt.hostvalue[49].mLen = 21;
    ulpSqlstmt.hostvalue[49].mMaxlen = sizeof(k50);
    ulpSqlstmt.hostvalue[49].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[49].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[49].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[50].mHostVar = (void*)(k51);
    ulpSqlstmt.hostvalue[50].mHostInd = NULL;
    ulpSqlstmt.hostvalue[50].isarr = 0;
    ulpSqlstmt.hostvalue[50].mType = 6;
    ulpSqlstmt.hostvalue[50].isstruct = 0;
    ulpSqlstmt.hostvalue[50].mSizeof = 0;
    ulpSqlstmt.hostvalue[50].mLen = 12;
    ulpSqlstmt.hostvalue[50].mMaxlen = sizeof(k51);
    ulpSqlstmt.hostvalue[50].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[50].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[50].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[51].mHostVar = (void*)&(k52);
    ulpSqlstmt.hostvalue[51].mHostInd = NULL;
    ulpSqlstmt.hostvalue[51].isarr = 0;
    ulpSqlstmt.hostvalue[51].mType = 2;
    ulpSqlstmt.hostvalue[51].isstruct = 0;
    ulpSqlstmt.hostvalue[51].mSizeof = sizeof(int);
    ulpSqlstmt.hostvalue[51].mLen = 0;
    ulpSqlstmt.hostvalue[51].mMaxlen = 0;
    ulpSqlstmt.hostvalue[51].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[51].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[51].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[52].mHostVar = (void*)&(k53);
    ulpSqlstmt.hostvalue[52].mHostInd = NULL;
    ulpSqlstmt.hostvalue[52].isarr = 0;
    ulpSqlstmt.hostvalue[52].mType = 2;
    ulpSqlstmt.hostvalue[52].isstruct = 0;
    ulpSqlstmt.hostvalue[52].mSizeof = sizeof(int);
    ulpSqlstmt.hostvalue[52].mLen = 0;
    ulpSqlstmt.hostvalue[52].mMaxlen = 0;
    ulpSqlstmt.hostvalue[52].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[52].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[52].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[53].mHostVar = (void*)(k54);
    ulpSqlstmt.hostvalue[53].mHostInd = NULL;
    ulpSqlstmt.hostvalue[53].isarr = 0;
    ulpSqlstmt.hostvalue[53].mType = 6;
    ulpSqlstmt.hostvalue[53].isstruct = 0;
    ulpSqlstmt.hostvalue[53].mSizeof = 0;
    ulpSqlstmt.hostvalue[53].mLen = 12;
    ulpSqlstmt.hostvalue[53].mMaxlen = sizeof(k54);
    ulpSqlstmt.hostvalue[53].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[53].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[53].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[54].mHostVar = (void*)(k55);
    ulpSqlstmt.hostvalue[54].mHostInd = NULL;
    ulpSqlstmt.hostvalue[54].isarr = 0;
    ulpSqlstmt.hostvalue[54].mType = 6;
    ulpSqlstmt.hostvalue[54].isstruct = 0;
    ulpSqlstmt.hostvalue[54].mSizeof = 0;
    ulpSqlstmt.hostvalue[54].mLen = 21;
    ulpSqlstmt.hostvalue[54].mMaxlen = sizeof(k55);
    ulpSqlstmt.hostvalue[54].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[54].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[54].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[55].mHostVar = (void*)(k56);
    ulpSqlstmt.hostvalue[55].mHostInd = NULL;
    ulpSqlstmt.hostvalue[55].isarr = 0;
    ulpSqlstmt.hostvalue[55].mType = 6;
    ulpSqlstmt.hostvalue[55].isstruct = 0;
    ulpSqlstmt.hostvalue[55].mSizeof = 0;
    ulpSqlstmt.hostvalue[55].mLen = 21;
    ulpSqlstmt.hostvalue[55].mMaxlen = sizeof(k56);
    ulpSqlstmt.hostvalue[55].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[55].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[55].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[56].mHostVar = (void*)(k57);
    ulpSqlstmt.hostvalue[56].mHostInd = NULL;
    ulpSqlstmt.hostvalue[56].isarr = 0;
    ulpSqlstmt.hostvalue[56].mType = 6;
    ulpSqlstmt.hostvalue[56].isstruct = 0;
    ulpSqlstmt.hostvalue[56].mSizeof = 0;
    ulpSqlstmt.hostvalue[56].mLen = 21;
    ulpSqlstmt.hostvalue[56].mMaxlen = sizeof(k57);
    ulpSqlstmt.hostvalue[56].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[56].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[56].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[57].mHostVar = (void*)&(k58);
    ulpSqlstmt.hostvalue[57].mHostInd = NULL;
    ulpSqlstmt.hostvalue[57].isarr = 0;
    ulpSqlstmt.hostvalue[57].mType = 14;
    ulpSqlstmt.hostvalue[57].isstruct = 0;
    ulpSqlstmt.hostvalue[57].mSizeof = sizeof(double);
    ulpSqlstmt.hostvalue[57].mLen = 0;
    ulpSqlstmt.hostvalue[57].mMaxlen = 0;
    ulpSqlstmt.hostvalue[57].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[57].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[57].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[58].mHostVar = (void*)&(k59);
    ulpSqlstmt.hostvalue[58].mHostInd = NULL;
    ulpSqlstmt.hostvalue[58].isarr = 0;
    ulpSqlstmt.hostvalue[58].mType = 2;
    ulpSqlstmt.hostvalue[58].isstruct = 0;
    ulpSqlstmt.hostvalue[58].mSizeof = sizeof(int);
    ulpSqlstmt.hostvalue[58].mLen = 0;
    ulpSqlstmt.hostvalue[58].mMaxlen = 0;
    ulpSqlstmt.hostvalue[58].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[58].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[58].mIsDynAlloc = (short) 0;
    ulpSqlstmt.hostvalue[59].mHostVar = (void*)(k60);
    ulpSqlstmt.hostvalue[59].mHostInd = NULL;
    ulpSqlstmt.hostvalue[59].isarr = 0;
    ulpSqlstmt.hostvalue[59].mType = 6;
    ulpSqlstmt.hostvalue[59].isstruct = 0;
    ulpSqlstmt.hostvalue[59].mSizeof = 0;
    ulpSqlstmt.hostvalue[59].mLen = 301;
    ulpSqlstmt.hostvalue[59].mMaxlen = sizeof(k60);
    ulpSqlstmt.hostvalue[59].mUnsign = (short) 0;
    ulpSqlstmt.hostvalue[59].mInOut = (short) 0;
    ulpSqlstmt.hostvalue[59].mIsDynAlloc = (short) 0;
    ulpDoEmsql( (char*) connection, &ulpSqlstmt, NULL );
}

            ASSERT_SQL;
            
            assert( gettimeofday( &endTime, NULL ) == 0 );
            
            if ( endTime.tv_usec > startTime.tv_usec ) {
                elapsed = ( endTime.tv_sec  - startTime.tv_sec ) * 1000000 + ( endTime.tv_usec - startTime.tv_usec );
            } else {
                elapsed = ( endTime.tv_sec  - 1 - startTime.tv_sec ) * 1000000 + ( endTime.tv_usec + 1000000 - startTime.tv_usec );
            }
            
            if ( context->minimum > elapsed ) context->minimum = elapsed;
            if ( context->maximum < elapsed ) context->maximum = elapsed;
            context->sum += elapsed;
            context->numberOfTransactions++;
            if ( elapsed >= threshold ) context->numberOfLongTransactions++;
            
        }
        
    }
    
    /*                 DISCONNECT; */
{
    struct ulpSqlstmt ulpSqlstmt;
    memset(&ulpSqlstmt, 0, sizeof(ulpSqlstmt));
    ulpSqlstmt.stmttype = 2;
    ulpSqlstmt.stmtname = NULL;
    ulpSqlstmt.ismt = 1;
    ulpSqlstmt.numofhostvar = 0;
    ulpSqlstmt.esqlopts    = _esqlopts;
    ulpSqlstmt.sqlcaerr    = &sqlca;
    ulpSqlstmt.sqlcodeerr  = &SQLCODE;
    ulpSqlstmt.sqlstateerr = ulpGetSqlstate();
    ulpDoEmsql( (char*) connection, &ulpSqlstmt, NULL );
}

    ASSERT_SQL;
    
    return argument;
    
}

int main( int argc, char* argv[] ) {
    
    threadContext*      contexts;
    pthread_attr_t      threadAttribute;
    int                 thread;
    pthread_t*          threads;
    void*               value;
    struct tm*          tm;
    long long           second;
    long long           usecond;
    long long           elapsed;
    double              tps;
    int                 minimum;
    int                 maximum;
    long long           sum;
    int                 numberOfLongTransactions;
    int                 average;
    double              LongTransaction;
/*    
    numberOfThreads      = 1;
    startValue           = 0;
    numberOfTransactions = 1000000;
    sizeOfUnit           = 1000;
    threshold            = 1000000;
    cap                  = 0;
    strcpy( user,          "SYS" );
    strcpy( password,      "MANAGER" );
    strcpy( option,        "DSN=localhost;PORT_NO=20300;CONN_TYPE=2" );
*/    
    cap = 0;

    switch( argc ) {
     case 10:
        strcpy( option,        argv[9] );
     case 9:
        strcpy( password,      argv[8] );
     case 8:
        strcpy( user,          argv[7] );
     case 7:
        strcpy( test_mode,     argv[6] );
     case 6:
        threshold            = atoi( argv[5] );
     case 5:
        sizeOfUnit           = atoi( argv[4] );
     case 4:
        numberOfTransactions = atoi( argv[3] );
     case 3:
        startValue           = atoi( argv[2] );
     case 2:
        numberOfThreads      = atoi( argv[1] );
        break;
     default:
        printf( "Usage: %s numberOfThreads [startValue] [numberOfTransactions] [sizeOfUnit] [threshold] [test_mode] [user] [password] [option]\n", argv[0] );
        exit( EXIT_FAILURE );
        break;
    }
    
    printf( "Working Directory                 : %s\n",  workingDirectory()   );
    printf( "Test Mode                         : %s\n",  test_mode            );
    printf( "Number of Threads                 : %8d\n", numberOfThreads      );
    printf( "Start Value                       : %8d\n", startValue           );
    printf( "Number of Transactions            : %8d\n", numberOfTransactions );
    printf( "Size   of Unit                    : %8d\n", sizeOfUnit           );
    printf( "Threshold(microsecond)            : %8d\n", threshold            );
    printf( "Cap(TPS)                          : %8d\n", cap                  );
    printf( "User                              : %s\n",  user                 );
    printf( "Password                          : %s\n",  password             );
    printf( "Option                            : %s\n",  option               );
    
    contexts = malloc( sizeof(threadContext) * numberOfThreads );
    assert( contexts != NULL );
    memset( contexts, 0, sizeof(threadContext) * numberOfThreads );
    for ( thread = 0; thread < numberOfThreads; thread++ ) {
        assert( pthread_mutex_init( &(contexts[thread].connected), NULL ) == 0 );
        sprintf( contexts[thread].connection, "%d", thread );
        contexts[thread].minimum                  = INT_MAX;
        contexts[thread].maximum                  = 0;
        contexts[thread].sum                      = 0;
        contexts[thread].numberOfTransactions     = 0;
        contexts[thread].numberOfLongTransactions = 0;
    }
    
    threads = malloc( sizeof(pthread_t) * numberOfThreads );
    assert( threads != NULL );
    
    mutex = malloc( sizeof(pthread_mutex_t) );
    assert( mutex != NULL );
    remain = malloc( sizeof(int) );
    assert( remain != NULL );
    cursor = malloc( sizeof(int) );
    assert( cursor != NULL );
    allocated = malloc( sizeof(int) );
    assert( allocated != NULL );
    
    assert( pthread_mutex_init( mutex, NULL ) == 0 );
    
    *remain    = numberOfTransactions;
    *cursor    = startValue;
    *allocated = 0;
    
    assert( pthread_attr_init( &threadAttribute ) == 0 );
    assert( pthread_attr_setscope( &threadAttribute, PTHREAD_SCOPE_SYSTEM ) == 0 );
    
    fflush( stdout );
    fflush( stderr );

    assert( gettimeofday( &connectTime, NULL ) == 0 );

    assert( pthread_mutex_lock( mutex ) == 0 );

    for ( thread = 0; thread < numberOfThreads; thread++ ) {
        assert( pthread_mutex_lock( &(contexts[thread].connected) ) == 0 );
        assert( pthread_create( threads + thread, &threadAttribute, worker, contexts + thread ) == 0 );
    }

    for ( thread = 0; thread < numberOfThreads; thread++ ) {
        assert( pthread_mutex_lock( &(contexts[thread].connected) ) == 0 );
        assert( pthread_mutex_unlock( &(contexts[thread].connected) ) == 0 );
    }

    assert( gettimeofday( &startTime, NULL ) == 0 );
    if ( startTime.tv_usec > connectTime.tv_usec ) {
        second  = startTime.tv_sec  - connectTime.tv_sec;
        usecond = startTime.tv_usec - connectTime.tv_usec;
    } else {
        second  = startTime.tv_sec  -       1 - connectTime.tv_sec;
        usecond = startTime.tv_usec + 1000000 - connectTime.tv_usec;
    }
    printf( "Connection Elapsed                : %llu.%06llu second\n", second, usecond );
    tm = localtime( &(startTime.tv_sec) );
    printf( "Start Time                        : %04u/%02u/%02u %02u:%02u:%02u.%06u\n", (unsigned int)(1900+tm->tm_year), (unsigned int)(tm->tm_mon+1), (unsigned int)(tm->tm_mday), (unsigned int)(tm->tm_hour), (unsigned int)(tm->tm_min), (unsigned int)(tm->tm_sec), (unsigned int)(startTime.tv_usec) );
    
    assert( pthread_mutex_unlock( mutex ) == 0 );
    
    fflush( stdout );
    fflush( stderr );
    
    for ( thread = 0; thread < numberOfThreads; thread++ ) {
        assert( pthread_join( threads[thread], &value ) == 0 );
    }
    
    assert( gettimeofday( &endTime, NULL ) == 0 );
    tm = localtime( &(endTime.tv_sec) );
    printf( "End   Time                        : %04u/%02u/%02u %02u:%02u:%02u.%06u\n", (unsigned int)(1900+tm->tm_year), (unsigned int)(tm->tm_mon+1), (unsigned int)(tm->tm_mday), (unsigned int)(tm->tm_hour), (unsigned int)(tm->tm_min), (unsigned int)(tm->tm_sec), (unsigned int)(endTime.tv_usec) );
    
    assert( pthread_attr_destroy( &threadAttribute ) == 0 );
    
    assert( pthread_mutex_destroy( mutex ) == 0 );
    
    qsort( contexts, numberOfThreads, sizeof(threadContext), compareThreadContexts );
    
    minimum                  = INT_MAX;
    maximum                  = 0;
    sum                      = 0;
    numberOfLongTransactions = 0;
    for ( thread = 0; thread < numberOfThreads; thread++ ) {
        if ( minimum > contexts[thread].minimum ) minimum = contexts[thread].minimum;
        if ( maximum < contexts[thread].maximum ) maximum = contexts[thread].maximum;
        sum                      += contexts[thread].sum;
        numberOfLongTransactions += contexts[thread].numberOfLongTransactions;
    }
    average = (int)( (double)sum / (double)numberOfTransactions );
    
    if ( endTime.tv_usec > startTime.tv_usec ) {
        second  = endTime.tv_sec  - startTime.tv_sec;
        usecond = endTime.tv_usec - startTime.tv_usec;
    } else {
        second  = endTime.tv_sec  -       1 - startTime.tv_sec;
        usecond = endTime.tv_usec + 1000000 - startTime.tv_usec;
    }
    printf( "Elapsed                           : %llu.%06llu second\n", second, usecond );
    
    elapsed = second * 1000000 + usecond;
    tps = (double)numberOfTransactions / ( (double)elapsed / 1e6 );
    LongTransaction = (double)numberOfLongTransactions / (double)numberOfTransactions * 100;
    printf( "Transactions per Second           : %9.2f TPS\n", tps );
    printf( "Minimum                           : %6d microseconds\n", minimum );
    printf( "Maximum                           : %6d microseconds\n", maximum );
    printf( "Average                           : %6d microseconds\n", average );
    printf( "Number of Long Transactions       : %6.2f%% ( %d / %d )\n", (double)numberOfLongTransactions / (double)numberOfTransactions * 100, numberOfLongTransactions, numberOfTransactions );
    printf( "Number of Transactions per Thread :" );
    for ( thread = 0; thread < numberOfThreads; thread++ ) {
        printf( " %d", contexts[thread].numberOfTransactions );
    }
    printf( "\n" );
    printf( "\n" );
    
    writeResult( test_mode, 2, numberOfThreads, tps, LongTransaction, minimum, maximum, average ); 
    return EXIT_SUCCESS;
    
}
